### ISSUE TITLE
Fail to read video files

### ISSUE THREAD

**Issue by Chun-Lin** [TadasBaltrusaitis/CLM-framework#10] opened 2015-09-13 03:12 UTC
Hi Tadas,

When I tried to use the demo videos in folder video to test the program, it just showed that the video can't be read. I typed ./bin/SimpleCLM -f "./videos/default.wmv" , and then it showed the error messages:

Attempting to read from file: ./videos/changeLighting.wmv
Segmentation fault (core dumped)

Is that something wrong?

Thank you,
Chun-Lin

**Comment by TadasBaltrusaitis** [comment] 2015-09-14 20:00
Hi Chin-Lin,

It was indeed a bug, it couldn't find one of the model files. It should be fixed now, just redo the cmake step and the build.

Let me know if it works now.

Thanks,
Tadas

**Comment by Chun-Lin** [comment] 2015-09-15 04:52
yes, it works!! Thank you so much!!

But I've found something wrong when I tried to run SimpleCLMImg. 
I typed ./bin/SimpleCLMImg -fdir "./videos/" -ofdir "./demo_img/" -oidir "./demo_img/" -clmwild
then it showed the error messages:

OpenCV Error: Unspecified error (could not find a writer for the specified extension) in imwrite_, file /home/gary/Documents/opencv-3.0.0-beta/modules/imgcodecs/src/loadsave.cpp, line 353
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/gary/Documents/opencv-3.0.0-beta/modules/imgcodecs/src/loadsave.cpp:353: error: (-2) could not find a writer for the specified extension in function imwrite_

I think there are something wrong with image writer or maybe some libraries that I've not installed, but I'm sure that I've install OpenCV correctly@@

Thank you,
Chun-Lin

**Comment by TadasBaltrusaitis** [comment] 2015-09-15 21:20
Hi,

I just attempted to run that piece of code and it runs fine my end.

It is attempting to write the images as .jpg, you can probably try changing that to .png in the code and seeing if it makes a difference. Alternatively, try no including the -oidir flag to see if the problem is only in the image writing part.

Thanks,
Tadas

**Closed** 2015-10-22 13:06 UTC
